version: '3.3'

services:
  db:
    image: mysql:8.0.15
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: jenkins
      MYSQL_USER: vasanth
      MYSQL_PASSWORD: laxmivasanth

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "7000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: vasanth
      WORDPRESS_DB_PASSWORD: laxmivasanth
      WORDPRESS_DB_NAME: jenkins
    volumes:
      - wordpress_data:/var/www/html

volumes:
  db_data:
  wordpress_data:
